# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install x11 dependencies
      run: sudo apt install -y libx11-dev xserver-xorg-dev xorg-dev

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v ./...
  
    - name: Upload build as artifact.
      uses: actions/upload-artifact@v4.6.2
      with:
        name: openstomp-builds 
        path: ./*
        warn: Output a warning but do not fail the action
        error: Fail the action with an error message
        ignore: Do not output any warnings or errors, the action does not fail
        retention-days: 90
